# model
model_name: rn18

# training
batch: 256
epochs: 200
optimizer: 'adam'
lr: 1.0e-3
gamma: 0.1
milestones:
- 100
- 150

# datalogging
data_dir: "/bigdata/f_mnist" 
logdir: "/bigdata/f_mnist/logs" 

# hardware
data_workers: 16
